version: 0.0.1
author: "AdrianJA"

data_sources:
  - name: "test_source_1"
    schema: "staging"
    tables:

      - table_name: "test_table_1"
        rules:
          - validator: "expect_column_values_to_not_be_null"
            config: 
              column: "col1"
          - validator: "expect_column_values_to_be_between"
            config:
              column: "col1"
              min_value: 0
              max_value: 100

      - table_name: "test_table_2"
        rules:
          - validator: "expect_column_values_to_not_be_null"
            config: 
              column: "col1"
          - validator: "expect_column_values_to_be_between"
            config:
              column: "col1"
              min_value: 0
              max_value: 100


  - name:
    schema:
    tables:

      - table_name:
        rules:
          - validator:
            config:
              column: "col2"
          - validator:
            config:
              column: "col3"
              min_value: 0
              max_value: 100

